[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  # App Configuration
  REACT_APP_NAME = "AI Realtor Assistant"
  REACT_APP_VERSION = "2.0.0"
  REACT_APP_ENVIRONMENT = "production"
  
  # Feature Flags
  REACT_APP_ENABLE_ANALYTICS = "true"
  REACT_APP_ENABLE_ERROR_REPORTING = "true"
  REACT_APP_ENABLE_PERFORMANCE_MONITORING = "true"
  
  # Cache Configuration
  REACT_APP_CACHE_EXPIRY_HOURS = "24"
  REACT_APP_MAX_CACHE_SIZE = "50"
  
  # UI Configuration
  REACT_APP_ENABLE_ANIMATIONS = "false"
  REACT_APP_ENABLE_OFFLINE_MODE = "true"
  REACT_APP_ENABLE_CACHING = "true"
  
  # Smart Filtering Configuration
  REACT_APP_ENABLE_SMART_FILTERING = "true"
  REACT_APP_ENABLE_NATURAL_LANGUAGE = "true"
  REACT_APP_ENABLE_FEATURE_EXTRACTION = "true"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific configurations
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_ENABLE_ANALYTICS = "true"
  REACT_APP_ENABLE_ANIMATIONS = "false"

[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "preview"
  REACT_APP_ENABLE_ANALYTICS = "false"
  REACT_APP_ENABLE_ANIMATIONS = "true"

[context.branch-deploy.environment]
  REACT_APP_ENVIRONMENT = "development"
  REACT_APP_ENABLE_ANALYTICS = "false"
  REACT_APP_ENABLE_ANIMATIONS = "true"
